CREATE TABLE stop_times (
[cu_id] VARCHAR(50) PRIMARY KEY,
[Branch] VARCHAR(50),
[Rt #] VARCHAR(50),
[Acct #] VARCHAR(50),
[Cust #] VARCHAR(50),
[Cust Name] VARCHAR(50),
[Average Stop Time] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.1] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.2] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.3] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.4] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.5] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.6] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.7] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.8] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.9] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.10] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.11] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.12] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.13] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.14] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.15] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.16] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.17] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.18] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.19] VARCHAR(50),
[Date :: Start / Stop :: StopTime :: TravelTime.20] VARCHAR(50)
)