CREATE TABLE revenue_analysis (
	[cu_id] VARCHAR(50) PRIMARY KEY,
	[Branch] VARCHAR(50),
	[Q1 Average] MONEY,
	[Q1 Average Deviation] MONEY,
	[Q1 High Deviation] MONEY,
	[Q1 Low Deviation] MONEY,
	[Q2 Average] MONEY,
	[Q2 Average Deviation] MONEY,
	[Q2 High Deviation] MONEY,
	[Q2 Low Deviation] MONEY,
	[Q3 Average] MONEY,
	[Q3 Average Deviation] MONEY,
	[Q3 High Deviation] MONEY,
	[Q3 Low Deviation] MONEY,
	[Q4 Average] MONEY,
	[Q4 Average Deviation] MONEY,
	[Q4 High Deviation] MONEY,
	[Q4 Low Deviation] MONEY
)